from odoo import models, fields, api, _
from odoo.exceptions import UserError
import logging

logger = logging.getLogger(__name__)

class PurchaseOrder(models.Model):
    _inherit = 'purchase.order'
    
    bid_ids = fields.One2many('purchase.bid', 'order_id', string='Vendor Bids')
    vendor_ids = fields.Many2many('res.partner', string='RFQ Vendors', domain=[('is_company', '=', True), ('supplier_rank', '>', 0)])
    is_rfq_multi_vendor = fields.Boolean(string='Multi-Vendor RFQ', default=False)
    
    def action_send_rfq_to_vendors(self):
        for order in self:
            if not order.vendor_ids:
                raise UserError(_("No vendors selected for this RFQ."))
            logger.info(f"Sending RFQ {order.name} to vendors: {order.vendor_ids.mapped('name')}")
        return True
